version: "3.7"
services:
  app:
    build: .
    image: neerajcrespo/ms_test
    container_name: ms_test_container
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      RAILS_ENV: production